{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Dec  6 14:56:13 2012) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,700,500);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(-1,-0.5642521,9,5.078268);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLogy();
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *dataClonenew = new TH1F("dataClonenew","",8,0,8);
   dataClonenew->SetBinContent(1,826);
   dataClonenew->SetBinContent(2,358);
   dataClonenew->SetBinContent(3,146);
   dataClonenew->SetBinContent(4,119);
   dataClonenew->SetBinContent(5,92);
   dataClonenew->SetBinContent(6,43);
   dataClonenew->SetBinContent(7,32);
   dataClonenew->SetBinContent(8,17);
   dataClonenew->SetBinError(1,28.74022);
   dataClonenew->SetBinError(2,18.92089);
   dataClonenew->SetBinError(3,12.08305);
   dataClonenew->SetBinError(4,10.90871);
   dataClonenew->SetBinError(5,9.591663);
   dataClonenew->SetBinError(6,6.557439);
   dataClonenew->SetBinError(7,5.656854);
   dataClonenew->SetBinError(8,4.123106);
   dataClonenew->SetMinimum(1);
   dataClonenew->SetMaximum(32660);
   dataClonenew->SetEntries(8);
   dataClonenew->SetStats(0);
   dataClonenew->SetMarkerStyle(20);
   dataClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   dataClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   dataClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   dataClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   dataClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   dataClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   dataClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   dataClonenew->GetXaxis()->SetBinLabel(8," Dijet ");
   dataClonenew->GetXaxis()->SetNdivisions(8);
   dataClonenew->GetXaxis()->SetLabelFont(42);
   dataClonenew->GetXaxis()->SetLabelSize(0.055);
   dataClonenew->GetXaxis()->SetTitleFont(42);
   dataClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   dataClonenew->GetYaxis()->SetLabelFont(42);
   dataClonenew->GetYaxis()->SetLabelSize(0.05);
   dataClonenew->GetYaxis()->SetTitleSize(0.05);
   dataClonenew->GetYaxis()->SetTitleFont(42);
   dataClonenew->Draw("9");
   
   TH1F *sig2bkg = new TH1F("sig2bkg","",8,0,8);
   sig2bkg->SetBinContent(1,808.65);
   sig2bkg->SetBinContent(2,342.5107);
   sig2bkg->SetBinContent(3,141.5748);
   sig2bkg->SetBinContent(4,119.6284);
   sig2bkg->SetBinContent(5,78.16727);
   sig2bkg->SetBinContent(6,38.15129);
   sig2bkg->SetBinContent(7,23.82039);
   sig2bkg->SetBinContent(8,6.30596);
   sig2bkg->SetBinError(1,31.56844);
   sig2bkg->SetBinError(2,24.07341);
   sig2bkg->SetBinError(3,16.13704);
   sig2bkg->SetBinError(4,15.08267);
   sig2bkg->SetBinError(5,12.23411);
   sig2bkg->SetBinError(6,8.533276);
   sig2bkg->SetBinError(7,6.843545);
   sig2bkg->SetBinError(8,3.593933);
   sig2bkg->SetEntries(8);
   sig2bkg->SetStats(0);
   sig2bkg->SetFillColor(5);
   sig2bkg->SetLineWidth(2);
   sig2bkg->SetLineColor(1);
   sig2bkg->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   sig2bkg->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   sig2bkg->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   sig2bkg->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   sig2bkg->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   sig2bkg->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   sig2bkg->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   sig2bkg->GetXaxis()->SetBinLabel(8," Dijet ");
   sig2bkg->GetXaxis()->SetNdivisions(8);
   sig2bkg->GetXaxis()->SetLabelFont(42);
   sig2bkg->GetXaxis()->SetLabelSize(0.055);
   sig2bkg->GetXaxis()->SetTitleFont(42);
   sig2bkg->GetYaxis()->SetTitle("Events / BDT Bin");
   sig2bkg->GetYaxis()->SetLabelFont(42);
   sig2bkg->GetYaxis()->SetLabelSize(0.05);
   sig2bkg->GetYaxis()->SetTitleSize(0.05);
   sig2bkg->GetYaxis()->SetTitleFont(42);
   sig2bkg->Draw("9sameE2");
   
   TH1F *sig1bkg = new TH1F("sig1bkg","",8,0,8);
   sig1bkg->SetBinContent(1,808.65);
   sig1bkg->SetBinContent(2,342.5107);
   sig1bkg->SetBinContent(3,141.5748);
   sig1bkg->SetBinContent(4,119.6284);
   sig1bkg->SetBinContent(5,78.16727);
   sig1bkg->SetBinContent(6,38.15129);
   sig1bkg->SetBinContent(7,23.82039);
   sig1bkg->SetBinContent(8,6.30596);
   sig1bkg->SetBinError(1,15.78422);
   sig1bkg->SetBinError(2,12.0367);
   sig1bkg->SetBinError(3,8.068519);
   sig1bkg->SetBinError(4,7.541337);
   sig1bkg->SetBinError(5,6.117057);
   sig1bkg->SetBinError(6,4.266638);
   sig1bkg->SetBinError(7,3.421772);
   sig1bkg->SetBinError(8,1.796966);
   sig1bkg->SetEntries(8);
   sig1bkg->SetStats(0);
   sig1bkg->SetFillColor(3);
   sig1bkg->SetLineWidth(2);
   sig1bkg->SetLineColor(1);
   sig1bkg->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   sig1bkg->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   sig1bkg->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   sig1bkg->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   sig1bkg->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   sig1bkg->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   sig1bkg->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   sig1bkg->GetXaxis()->SetBinLabel(8," Dijet ");
   sig1bkg->GetXaxis()->SetNdivisions(8);
   sig1bkg->GetXaxis()->SetLabelFont(42);
   sig1bkg->GetXaxis()->SetLabelSize(0.055);
   sig1bkg->GetXaxis()->SetTitleFont(42);
   sig1bkg->GetYaxis()->SetTitle("Events / BDT Bin");
   sig1bkg->GetYaxis()->SetLabelFont(42);
   sig1bkg->GetYaxis()->SetLabelSize(0.05);
   sig1bkg->GetYaxis()->SetTitleSize(0.05);
   sig1bkg->GetYaxis()->SetTitleFont(42);
   sig1bkg->Draw("9sameE2");
   
   TH1F *bkgClonenew = new TH1F("bkgClonenew","",8,0,8);
   bkgClonenew->SetBinContent(1,808.65);
   bkgClonenew->SetBinContent(2,342.5107);
   bkgClonenew->SetBinContent(3,141.5748);
   bkgClonenew->SetBinContent(4,119.6284);
   bkgClonenew->SetBinContent(5,78.16727);
   bkgClonenew->SetBinContent(6,38.15129);
   bkgClonenew->SetBinContent(7,23.82039);
   bkgClonenew->SetBinContent(8,6.30596);
   bkgClonenew->SetBinError(1,13.55544);
   bkgClonenew->SetBinError(2,11.5391);
   bkgClonenew->SetBinError(3,7.94334);
   bkgClonenew->SetBinError(4,7.445849);
   bkgClonenew->SetBinError(5,6.066908);
   bkgClonenew->SetBinError(6,4.249547);
   bkgClonenew->SetBinError(7,3.413471);
   bkgClonenew->SetBinError(8,1.795859);
   bkgClonenew->SetEntries(8);
   bkgClonenew->SetStats(0);
   bkgClonenew->SetLineColor(4);
   bkgClonenew->SetLineWidth(2);
   bkgClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   bkgClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   bkgClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   bkgClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   bkgClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   bkgClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   bkgClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   bkgClonenew->GetXaxis()->SetBinLabel(8," Dijet ");
   bkgClonenew->GetXaxis()->SetNdivisions(8);
   bkgClonenew->GetXaxis()->SetLabelFont(42);
   bkgClonenew->GetXaxis()->SetLabelSize(0.055);
   bkgClonenew->GetXaxis()->SetTitleFont(42);
   bkgClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   bkgClonenew->GetYaxis()->SetLabelFont(42);
   bkgClonenew->GetYaxis()->SetLabelSize(0.05);
   bkgClonenew->GetYaxis()->SetTitleSize(0.05);
   bkgClonenew->GetYaxis()->SetTitleFont(42);
   bkgClonenew->Draw("9samehist");
   
   TH1F *gghClonenew = new TH1F("gghClonenew","",8,0,8);
   gghClonenew->SetBinContent(1,15.62664);
   gghClonenew->SetBinContent(2,11.84893);
   gghClonenew->SetBinContent(3,6.6591);
   gghClonenew->SetBinContent(4,8.14094);
   gghClonenew->SetBinContent(5,7.56424);
   gghClonenew->SetBinContent(6,4.89398);
   gghClonenew->SetBinContent(7,4.40887);
   gghClonenew->SetBinContent(8,2.40433);
   gghClonenew->SetBinError(1,3.953055);
   gghClonenew->SetBinError(2,3.442227);
   gghClonenew->SetBinError(3,2.580523);
   gghClonenew->SetBinError(4,2.853233);
   gghClonenew->SetBinError(5,2.750316);
   gghClonenew->SetBinError(6,2.212234);
   gghClonenew->SetBinError(7,2.099731);
   gghClonenew->SetBinError(8,1.55059);
   gghClonenew->SetEntries(8);
   gghClonenew->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   gghClonenew->SetLineColor(ci);
   gghClonenew->SetLineWidth(2);
   gghClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   gghClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   gghClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   gghClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   gghClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   gghClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   gghClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   gghClonenew->GetXaxis()->SetBinLabel(8," Dijet ");
   gghClonenew->GetXaxis()->SetNdivisions(8);
   gghClonenew->GetXaxis()->SetLabelFont(42);
   gghClonenew->GetXaxis()->SetLabelSize(0.055);
   gghClonenew->GetXaxis()->SetTitleFont(42);
   gghClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   gghClonenew->GetYaxis()->SetLabelFont(42);
   gghClonenew->GetYaxis()->SetLabelSize(0.05);
   gghClonenew->GetYaxis()->SetTitleSize(0.05);
   gghClonenew->GetYaxis()->SetTitleFont(42);
   gghClonenew->Draw("9samehist");
   
   TH1F *dataClonenew = new TH1F("dataClonenew2","",8,0,8);
   dataClonenew->SetBinContent(1,826);
   dataClonenew->SetBinContent(2,358);
   dataClonenew->SetBinContent(3,146);
   dataClonenew->SetBinContent(4,119);
   dataClonenew->SetBinContent(5,92);
   dataClonenew->SetBinContent(6,43);
   dataClonenew->SetBinContent(7,32);
   dataClonenew->SetBinContent(8,17);
   dataClonenew->SetBinError(1,28.74022);
   dataClonenew->SetBinError(2,18.92089);
   dataClonenew->SetBinError(3,12.08305);
   dataClonenew->SetBinError(4,10.90871);
   dataClonenew->SetBinError(5,9.591663);
   dataClonenew->SetBinError(6,6.557439);
   dataClonenew->SetBinError(7,5.656854);
   dataClonenew->SetBinError(8,4.123106);
   dataClonenew->SetMinimum(1);
   dataClonenew->SetMaximum(32660);
   dataClonenew->SetEntries(8);
   dataClonenew->SetStats(0);
   dataClonenew->SetMarkerStyle(20);
   dataClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   dataClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   dataClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   dataClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   dataClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   dataClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   dataClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   dataClonenew->GetXaxis()->SetBinLabel(8," Dijet ");
   dataClonenew->GetXaxis()->SetNdivisions(8);
   dataClonenew->GetXaxis()->SetLabelFont(42);
   dataClonenew->GetXaxis()->SetLabelSize(0.055);
   dataClonenew->GetXaxis()->SetTitleFont(42);
   dataClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   dataClonenew->GetYaxis()->SetLabelFont(42);
   dataClonenew->GetYaxis()->SetLabelSize(0.05);
   dataClonenew->GetYaxis()->SetTitleSize(0.05);
   dataClonenew->GetYaxis()->SetTitleFont(42);
   dataClonenew->Draw("9sameP");
   
   TLegend *leg = new TLegend(0.5,0.55,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dataClonenew","Data","PLE");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("gghClonenew","Higgs, m_{H}=125.0 GeV","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("bkgClonenew","Background","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig1bkg","\pm 1\sigma","F");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig2bkg","\pm 2\sigma","F");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.15,0.82,"CMS preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.75,"#sqrt{s} = 7 TeV L = 5.1 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   leg = new TLegend(0.5,0.55,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("dataClonenew","Data","PLE");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("gghClonenew","Higgs, m_{H}=125.0 GeV","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("bkgClonenew","Background","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig1bkg","#pm 1#sigma","F");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig2bkg","#pm 2#sigma","F");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   leg->SetTextFont(42);
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
