{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Dec  6 15:08:56 2012) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,700,500);
   gStyle->SetOptStat(0);
   c1->SetHighLightColor(2);
   c1->Range(-1.125,-0.5828684,10.125,5.245815);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLogy();
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *dataClonenew = new TH1F("dataClonenew","",9,0,9);
   dataClonenew->SetBinContent(1,990);
   dataClonenew->SetBinContent(2,306);
   dataClonenew->SetBinContent(3,326);
   dataClonenew->SetBinContent(4,272);
   dataClonenew->SetBinContent(5,252);
   dataClonenew->SetBinContent(6,49);
   dataClonenew->SetBinContent(7,81);
   dataClonenew->SetBinContent(8,16);
   dataClonenew->SetBinContent(9,9);
   dataClonenew->SetBinError(1,31.46427);
   dataClonenew->SetBinError(2,17.49286);
   dataClonenew->SetBinError(3,18.05547);
   dataClonenew->SetBinError(4,16.49242);
   dataClonenew->SetBinError(5,15.87451);
   dataClonenew->SetBinError(6,7);
   dataClonenew->SetBinError(7,9);
   dataClonenew->SetBinError(8,4);
   dataClonenew->SetBinError(9,3);
   dataClonenew->SetMinimum(1);
   dataClonenew->SetMaximum(46020);
   dataClonenew->SetEntries(9);
   dataClonenew->SetStats(0);
   dataClonenew->SetMarkerStyle(20);
   dataClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   dataClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   dataClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   dataClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   dataClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   dataClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   dataClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   dataClonenew->GetXaxis()->SetBinLabel(8,"Loose Dijet");
   dataClonenew->GetXaxis()->SetBinLabel(9,"Tight Dijet");
   dataClonenew->GetXaxis()->SetNdivisions(9);
   dataClonenew->GetXaxis()->SetLabelFont(42);
   dataClonenew->GetXaxis()->SetLabelSize(0.055);
   dataClonenew->GetXaxis()->SetTitleFont(42);
   dataClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   dataClonenew->GetYaxis()->SetLabelFont(42);
   dataClonenew->GetYaxis()->SetLabelSize(0.05);
   dataClonenew->GetYaxis()->SetTitleSize(0.05);
   dataClonenew->GetYaxis()->SetTitleFont(42);
   dataClonenew->Draw("9");
   
   TH1F *sig2bkg = new TH1F("sig2bkg","",9,0,9);
   sig2bkg->SetBinContent(1,952.42);
   sig2bkg->SetBinContent(2,297.5547);
   sig2bkg->SetBinContent(3,331.9493);
   sig2bkg->SetBinContent(4,237.0993);
   sig2bkg->SetBinContent(5,239.1261);
   sig2bkg->SetBinContent(6,40.7939);
   sig2bkg->SetBinContent(7,61.11279);
   sig2bkg->SetBinContent(8,18.21183);
   sig2bkg->SetBinContent(9,5.26897);
   sig2bkg->SetBinError(1,37.66577);
   sig2bkg->SetBinError(2,23.255);
   sig2bkg->SetBinError(3,24.82306);
   sig2bkg->SetBinError(4,21.06317);
   sig2bkg->SetBinError(5,20.97778);
   sig2bkg->SetBinError(6,8.907281);
   sig2bkg->SetBinError(7,10.73291);
   sig2bkg->SetBinError(8,5.946323);
   sig2bkg->SetBinError(9,3.2863);
   sig2bkg->SetEntries(9);
   sig2bkg->SetStats(0);
   sig2bkg->SetFillColor(5);
   sig2bkg->SetLineWidth(2);
   sig2bkg->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   sig2bkg->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   sig2bkg->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   sig2bkg->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   sig2bkg->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   sig2bkg->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   sig2bkg->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   sig2bkg->GetXaxis()->SetBinLabel(8,"Loose Dijet");
   sig2bkg->GetXaxis()->SetBinLabel(9,"Tight Dijet");
   sig2bkg->GetXaxis()->SetNdivisions(9);
   sig2bkg->GetXaxis()->SetLabelFont(42);
   sig2bkg->GetXaxis()->SetLabelSize(0.055);
   sig2bkg->GetXaxis()->SetTitleFont(42);
   sig2bkg->GetYaxis()->SetTitle("Events / BDT Bin");
   sig2bkg->GetYaxis()->SetLabelFont(42);
   sig2bkg->GetYaxis()->SetLabelSize(0.05);
   sig2bkg->GetYaxis()->SetTitleSize(0.05);
   sig2bkg->GetYaxis()->SetTitleFont(42);
   sig2bkg->Draw("9sameE2");
   
   TH1F *sig1bkg = new TH1F("sig1bkg","",9,0,9);
   sig1bkg->SetBinContent(1,952.42);
   sig1bkg->SetBinContent(2,297.5547);
   sig1bkg->SetBinContent(3,331.9493);
   sig1bkg->SetBinContent(4,237.0993);
   sig1bkg->SetBinContent(5,239.1261);
   sig1bkg->SetBinContent(6,40.7939);
   sig1bkg->SetBinContent(7,61.11279);
   sig1bkg->SetBinContent(8,18.21183);
   sig1bkg->SetBinContent(9,5.26897);
   sig1bkg->SetBinError(1,18.83289);
   sig1bkg->SetBinError(2,11.6275);
   sig1bkg->SetBinError(3,12.41153);
   sig1bkg->SetBinError(4,10.53159);
   sig1bkg->SetBinError(5,10.48889);
   sig1bkg->SetBinError(6,4.45364);
   sig1bkg->SetBinError(7,5.366455);
   sig1bkg->SetBinError(8,2.973161);
   sig1bkg->SetBinError(9,1.64315);
   sig1bkg->SetEntries(9);
   sig1bkg->SetStats(0);
   sig1bkg->SetFillColor(3);
   sig1bkg->SetLineWidth(2);
   sig1bkg->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   sig1bkg->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   sig1bkg->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   sig1bkg->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   sig1bkg->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   sig1bkg->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   sig1bkg->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   sig1bkg->GetXaxis()->SetBinLabel(8,"Loose Dijet");
   sig1bkg->GetXaxis()->SetBinLabel(9,"Tight Dijet");
   sig1bkg->GetXaxis()->SetNdivisions(9);
   sig1bkg->GetXaxis()->SetLabelFont(42);
   sig1bkg->GetXaxis()->SetLabelSize(0.055);
   sig1bkg->GetXaxis()->SetTitleFont(42);
   sig1bkg->GetYaxis()->SetTitle("Events / BDT Bin");
   sig1bkg->GetYaxis()->SetLabelFont(42);
   sig1bkg->GetYaxis()->SetLabelSize(0.05);
   sig1bkg->GetYaxis()->SetTitleSize(0.05);
   sig1bkg->GetYaxis()->SetTitleFont(42);
   sig1bkg->Draw("9sameE2");
   
   TH1F *bkgClonenew = new TH1F("bkgClonenew","",9,0,9);
   bkgClonenew->SetBinContent(1,952.42);
   bkgClonenew->SetBinContent(2,297.5547);
   bkgClonenew->SetBinContent(3,331.9493);
   bkgClonenew->SetBinContent(4,237.0993);
   bkgClonenew->SetBinContent(5,239.1261);
   bkgClonenew->SetBinContent(6,40.7939);
   bkgClonenew->SetBinContent(7,61.11279);
   bkgClonenew->SetBinContent(8,18.21183);
   bkgClonenew->SetBinContent(9,5.26897);
   bkgClonenew->SetBinError(1,16.24707);
   bkgClonenew->SetBinError(2,11.24032);
   bkgClonenew->SetBinError(3,11.95939);
   bkgClonenew->SetBinError(4,10.26122);
   bkgClonenew->SetBinError(5,10.21267);
   bkgClonenew->SetBinError(6,4.434918);
   bkgClonenew->SetBinError(7,5.331544);
   bkgClonenew->SetBinError(8,2.967578);
   bkgClonenew->SetBinError(9,1.642305);
   bkgClonenew->SetEntries(9);
   bkgClonenew->SetStats(0);
   bkgClonenew->SetLineColor(4);
   bkgClonenew->SetLineWidth(2);
   bkgClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   bkgClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   bkgClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   bkgClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   bkgClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   bkgClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   bkgClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   bkgClonenew->GetXaxis()->SetBinLabel(8,"Loose Dijet");
   bkgClonenew->GetXaxis()->SetBinLabel(9,"Tight Dijet");
   bkgClonenew->GetXaxis()->SetNdivisions(9);
   bkgClonenew->GetXaxis()->SetLabelFont(42);
   bkgClonenew->GetXaxis()->SetLabelSize(0.055);
   bkgClonenew->GetXaxis()->SetTitleFont(42);
   bkgClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   bkgClonenew->GetYaxis()->SetLabelFont(42);
   bkgClonenew->GetYaxis()->SetLabelSize(0.05);
   bkgClonenew->GetYaxis()->SetTitleSize(0.05);
   bkgClonenew->GetYaxis()->SetTitleFont(42);
   bkgClonenew->Draw("9samehist");
   
   TH1F *gghClonenew = new TH1F("gghClonenew","",9,0,9);
   gghClonenew->SetBinContent(1,17.76562);
   gghClonenew->SetBinContent(2,7.58071);
   gghClonenew->SetBinContent(3,10.7175);
   gghClonenew->SetBinContent(4,11.06515);
   gghClonenew->SetBinContent(5,14.23028);
   gghClonenew->SetBinContent(6,3.40405);
   gghClonenew->SetBinContent(7,7.85525);
   gghClonenew->SetBinContent(8,2.08624);
   gghClonenew->SetBinContent(9,2.0011);
   gghClonenew->SetBinError(1,4.214928);
   gghClonenew->SetBinError(2,2.753309);
   gghClonenew->SetBinError(3,3.273759);
   gghClonenew->SetBinError(4,3.326432);
   gghClonenew->SetBinError(5,3.772304);
   gghClonenew->SetBinError(6,1.845007);
   gghClonenew->SetBinError(7,2.802722);
   gghClonenew->SetBinError(8,1.444382);
   gghClonenew->SetBinError(9,1.414602);
   gghClonenew->SetEntries(9);
   gghClonenew->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   gghClonenew->SetLineColor(ci);
   gghClonenew->SetLineWidth(2);
   gghClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   gghClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   gghClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   gghClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   gghClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   gghClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   gghClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   gghClonenew->GetXaxis()->SetBinLabel(8,"Loose Dijet");
   gghClonenew->GetXaxis()->SetBinLabel(9,"Tight Dijet");
   gghClonenew->GetXaxis()->SetNdivisions(9);
   gghClonenew->GetXaxis()->SetLabelFont(42);
   gghClonenew->GetXaxis()->SetLabelSize(0.055);
   gghClonenew->GetXaxis()->SetTitleFont(42);
   gghClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   gghClonenew->GetYaxis()->SetLabelFont(42);
   gghClonenew->GetYaxis()->SetLabelSize(0.05);
   gghClonenew->GetYaxis()->SetTitleSize(0.05);
   gghClonenew->GetYaxis()->SetTitleFont(42);
   gghClonenew->Draw("9samehist");
   
   TH1F *dataClonenew = new TH1F("dataClonenew2","",9,0,9);
   dataClonenew->SetBinContent(1,990);
   dataClonenew->SetBinContent(2,306);
   dataClonenew->SetBinContent(3,326);
   dataClonenew->SetBinContent(4,272);
   dataClonenew->SetBinContent(5,252);
   dataClonenew->SetBinContent(6,49);
   dataClonenew->SetBinContent(7,81);
   dataClonenew->SetBinContent(8,16);
   dataClonenew->SetBinContent(9,9);
   dataClonenew->SetBinError(1,31.46427);
   dataClonenew->SetBinError(2,17.49286);
   dataClonenew->SetBinError(3,18.05547);
   dataClonenew->SetBinError(4,16.49242);
   dataClonenew->SetBinError(5,15.87451);
   dataClonenew->SetBinError(6,7);
   dataClonenew->SetBinError(7,9);
   dataClonenew->SetBinError(8,4);
   dataClonenew->SetBinError(9,3);
   dataClonenew->SetMinimum(1);
   dataClonenew->SetMaximum(46020);
   dataClonenew->SetEntries(9);
   dataClonenew->SetStats(0);
   dataClonenew->SetMarkerStyle(20);
   dataClonenew->GetXaxis()->SetBinLabel(1,"BDT Bin 1 ");
   dataClonenew->GetXaxis()->SetBinLabel(2,"BDT Bin 2 ");
   dataClonenew->GetXaxis()->SetBinLabel(3,"BDT Bin 3 ");
   dataClonenew->GetXaxis()->SetBinLabel(4,"BDT Bin 4 ");
   dataClonenew->GetXaxis()->SetBinLabel(5,"BDT Bin 5 ");
   dataClonenew->GetXaxis()->SetBinLabel(6,"BDT Bin 6 ");
   dataClonenew->GetXaxis()->SetBinLabel(7,"BDT Bin 7 ");
   dataClonenew->GetXaxis()->SetBinLabel(8,"Loose Dijet");
   dataClonenew->GetXaxis()->SetBinLabel(9,"Tight Dijet");
   dataClonenew->GetXaxis()->SetNdivisions(9);
   dataClonenew->GetXaxis()->SetLabelFont(42);
   dataClonenew->GetXaxis()->SetLabelSize(0.055);
   dataClonenew->GetXaxis()->SetTitleFont(42);
   dataClonenew->GetYaxis()->SetTitle("Events / BDT Bin");
   dataClonenew->GetYaxis()->SetLabelFont(42);
   dataClonenew->GetYaxis()->SetLabelSize(0.05);
   dataClonenew->GetYaxis()->SetTitleSize(0.05);
   dataClonenew->GetYaxis()->SetTitleFont(42);
   dataClonenew->Draw("9sameP");
   
   TLegend *leg = new TLegend(0.5,0.55,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dataClonenew","Data","PLE");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("gghClonenew","Higgs, m_{H}=125.0 GeV","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("bkgClonenew","Background","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig1bkg","\pm 1\sigma","F");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig2bkg","\pm 2\sigma","F");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.15,0.82,"CMS preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.75,"#sqrt{s} = 8 TeV L = 5.3 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   leg = new TLegend(0.5,0.55,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("dataClonenew","Data","PLE");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("gghClonenew","Higgs, m_{H}=125.0 GeV","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("bkgClonenew","Background","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig1bkg","#pm 1#sigma","F");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("sig2bkg","#pm 2#sigma","F");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   leg->SetTextFont(42);
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
